name: .NET Framework CI with Allure

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install NuGet CLI
        uses: NuGet/setup-nuget@v1.1.1

      - name: Restore NuGet packages
        run: nuget restore CommandPatternCalculator.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build the solution
        run: msbuild CommandPatternCalculator.sln /p:Configuration=Release

      - name: Run tests and export .trx
        run: dotnet test --no-build --configuration Release --logger "trx" --verbosity normal

      - name: Install trx2allure tool
        run: dotnet tool install --global trx2allure

      - name: Convert .trx to Allure format
        run: trx2allure "**/TestResults/*.trx" -o allure-results

      - name: Download Allure CLI
        run: |
          curl -L -o allure.zip https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip
          powershell -command "Expand-Archive -Path allure.zip -DestinationPath allure-cli"
          echo "${{ github.workspace }}\\allure-cli\\allure-2.27.0\\bin" >> $env:GITHUB_PATH

      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  deploy-report:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Allure report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
