name: .NET Framework CI with Allure

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install NuGet CLI
        uses: NuGet/setup-nuget@v1.1.1

      - name: Restore NuGet packages
        run: nuget restore CommandPatternCalculator.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build the solution using MSBuild
        run: msbuild CommandPatternCalculator.sln /p:Configuration=Release

      - name: Add Allure.Xunit NuGet package
        run: nuget install Allure.Xunit -OutputDirectory packages

      - name: Install Allure CLI via Scoop
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
          irm get.scoop.sh | iex
          scoop install allure

      - name: Run tests with Allure attributes
        run: |
          mkdir allure-results
          dotnet test --no-build --configuration Release --results-directory allure-results --logger:"xunit"

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload test results (Allure)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Upload Allure report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  deploy-report:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Allure report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
