name: .NET Framework CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install NuGet CLI
        uses: NuGet/setup-nuget@v1.1.1

      - name: Restore NuGet packages
        run: nuget restore CommandPatternCalculator.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build the solution using MSBuild
        run: msbuild CommandPatternCalculator.sln /p:Configuration=Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --logger "trx" --verbosity normal

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate HTML test report
        run: reportgenerator -reports:**/TestResults/*.trx -targetdir:TestReport -reporttypes:HtmlInline_AzurePipelines

      - name: Upload test results (TRX)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/TestResults/*.trx'

      - name: Upload test report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: TestReport

  deploy-report:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download test report artifact
        uses: actions/download-artifact@v4
        with:
          name: test-report
          path: TestReport

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./TestReport
          publish_branch: gh-pages
