name: .NET Framework CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install NuGet CLI
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore CommandPatternCalculator.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build the solution using MSBuild
        run: msbuild CommandPatternCalculator.sln /p:Configuration=Release

      - name: Run tests using VSTest
        run: |
          vstest.console.exe CommandPatternCalculator\bin\Release\CommandPatternCalculator.exe /Logger:trx

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/*.trx'
